from pathlib import Path

PROJECT_NAME = "twitter"

DEFAULT_TWITTER_USER_NAME = ""
DEFAULT_TWITTER_USER_ID = ""

DEFAULT_SLACK_CHANNEL_ID = ""
DEFAULT_SLACK_ICON = ""

FILENAME_SEPARATOR = "____"
OUTPUT_FOLDER_PATH = Path(f"data/")

COMPARE_FOLLOWERS_SLEEP_INTERVAL = 10 * 60

USERS_TO_MONITOR = []