from pathlib import Path


PROJECT_NAME = "twitter"

DEFAULT_TWITTER_USER_NAME = "stedogin"
DEFAULT_TWITTER_USER_ID = "831625598174896129"

DEFAULT_SLACK_CHANNEL_ID = "CDUMBKV7A"
DEFAULT_SLACK_ICON = ":space_invader:"

FILENAME_SEPARATOR = "____"
OUTPUT_FOLDER_PATH = Path(f"data/")

COMPARE_FOLLOWERS_SLEEP_INTERVAL = 1 * 60
